version: "3.8"

services:
  producer:
    container_name: dataweave-producer
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JAVA_OPTS: "-Xms1g -Xmx1g -XX:+UseG1GC"
    volumes:
      - ./logs/web:/app/logs
