# =========================
# App server configs
# =========================
spring.application.name=dataweave-api
server.port=9111
kafka.producer.worker-count=1
log.probability=0.5


# =========================
# logging configs for the
# =========================
logging.file.name=/path/to/dir
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7


# =========================
# Spring Kafka
# =========================
spring.kafka.bootstrap-servers=localhost:9093
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.retries=3
spring.kafka.producer.properties.enable.idempotence=true


# =========================
# Monitoring
# =========================
# Expose Prometheus actuator endpoint
management.endpoints.web.exposure.include=health,info,prometheus

# Enable Prometheus export (default true)
management.metrics.export.prometheus.enabled=true

# Optional: add common tags
management.metrics.tags.application=kafka-producer-app